export type ArticleCategory = "getting-started" | "inbox-setup" | "campaigns" | "troubleshooting";

export interface Article {
  id: string;
  slug: string;
  title: string;
  category: ArticleCategory;
  content: string;
  tags: string[];
}

export const articles: Article[] = [
  // ── Getting Started ──────────────────────────────────────────────────────
  {
    id: "gs-1",
    slug: "welcome-to-convergeflow",
    title: "Welcome to ConvergeFlow",
    category: "getting-started",
    content: [
      "# Welcome to ConvergeFlow",
      "",
      "ConvergeFlow is an AI-powered cold email platform that helps you connect your domain, warm up inboxes, and send personalized outreach at scale.",
      "",
      "## How it works",
      "",
      "1. **Connect your domain** - Add DNS records to authenticate your sending address.",
      "2. **Set up an inbox** - Connect Gmail, Outlook, or a custom SMTP provider.",
      "3. **Import leads** - Upload a CSV or pull from our integrations.",
      "4. **Create a campaign** - Choose a writing style and let AI draft your sequences.",
      "5. **Watch replies come in** - Interested leads are surfaced automatically.",
      "",
      "## What you need to get started",
      "",
      "- A website domain you control (or we can provision one for you)",
      "- An email account you want to send from",
      "- A list of target contacts",
    ].join("\n"),
    tags: ["onboarding", "setup", "overview"],
  },
  {
    id: "gs-2",
    slug: "connecting-your-domain",
    title: "Connecting Your Domain",
    category: "getting-started",
    content: [
      "# Connecting Your Domain",
      "",
      "Connecting a domain lets ConvergeFlow authenticate your emails so they land in the inbox instead of spam.",
      "",
      "## Why domain authentication matters",
      "",
      "Email providers (Gmail, Outlook) check three DNS records before they trust an email:",
      "",
      "- **SPF** - proves the server is allowed to send for your domain",
      "- **DKIM** - cryptographic signature that proves the email was not tampered with",
      "- **DMARC** - policy that tells receivers what to do with unauthenticated mail",
      "",
      "## Steps",
      "",
      "1. Go to **Onboarding > Domain** or **Settings > Domains**.",
      "2. Select *Use my own website* and enter your root domain (e.g. acme.com).",
      "3. Copy the three DNS records shown and add them to your DNS provider.",
      "4. Click **Verify & Continue** - DNS propagation can take up to 24 hours.",
      "",
      "## Using a ConvergeFlow subdomain",
      "",
      "If you don't want to touch your DNS, select *Use a ConvergeFlow address*. We'll provision a subdomain and handle all the authentication for you.",
    ].join("\n"),
    tags: ["domain", "DNS", "SPF", "DKIM", "DMARC", "authentication"],
  },
  {
    id: "gs-3",
    slug: "importing-leads",
    title: "Importing Leads via CSV",
    category: "getting-started",
    content: [
      "# Importing Leads via CSV",
      "",
      "ConvergeFlow can import leads from a CSV file in seconds.",
      "",
      "## Required columns",
      "",
      "Your CSV must include at least one of: email, firstName, lastName.",
      "Optional but recommended: company, title, industry, location.",
      "",
      "## How to import",
      "",
      "1. Go to **Customers** and click **Import CSV**.",
      "2. Upload your file (max 10 MB, up to 50,000 rows).",
      "3. Map each CSV column to a ConvergeFlow field.",
      "4. Click **Import** - new leads appear instantly.",
      "",
      "## Deduplication",
      "",
      "We automatically skip rows where the email already exists in your account. Existing leads are never overwritten.",
      "",
      "## Lead scoring",
      "",
      "After import, ConvergeFlow scores each lead 1-10 based on company size, industry fit, and recency signals.",
    ].join("\n"),
    tags: ["csv", "import", "leads", "contacts"],
  },

  // ── Inbox Setup ──────────────────────────────────────────────────────────
  {
    id: "inbox-1",
    slug: "connecting-gmail",
    title: "Connecting a Gmail Account",
    category: "inbox-setup",
    content: [
      "# Connecting a Gmail Account",
      "",
      "Connecting Gmail takes one click and lets ConvergeFlow send emails on your behalf.",
      "",
      "## Steps",
      "",
      "1. Go to **Settings > Connected Inboxes** and click **+ Add Inbox**.",
      "2. Select **Gmail**.",
      "3. You'll be redirected to Google's OAuth consent screen.",
      "4. Grant the *Send email on your behalf* permission.",
      "5. You're returned to ConvergeFlow - your inbox shows as **Connected**.",
      "",
      "## What permissions we request",
      "",
      "- gmail.send - send emails from your account",
      "- gmail.readonly - detect replies so we can stop sequences automatically",
      "",
      "We do **not** request access to read, delete, or modify your existing emails.",
      "",
      "## Troubleshooting",
      "",
      "If the OAuth redirect fails, try in an incognito window. If you get a 'not verified' warning, continue past it - the app is in the process of Google verification.",
    ].join("\n"),
    tags: ["gmail", "inbox", "oauth", "email"],
  },
  {
    id: "inbox-2",
    slug: "inbox-warmup",
    title: "Understanding Inbox Warmup",
    category: "inbox-setup",
    content: [
      "# Understanding Inbox Warmup",
      "",
      "Before ConvergeFlow sends cold emails from your inbox, we warm it up to build sender reputation.",
      "",
      "## What warmup does",
      "",
      "Warmup sends a low volume of real emails between trusted accounts and automatically marks them as 'not spam'. This signals to Gmail and Outlook that your inbox is legitimate.",
      "",
      "## Duration",
      "",
      "Warmup runs for **14 days** by default. You can start campaigns before warmup completes, but higher deliverability is achieved after day 7.",
      "",
      "## Daily sending ramp",
      "",
      "Days 1-3: 10 emails per day",
      "Days 4-7: 30 emails per day",
      "Days 8-14: 75 emails per day",
      "Day 15+: 150 emails per day",
      "",
      "## Monitoring warmup",
      "",
      "Go to **Deliverability** to see your current warmup score and any flags.",
    ].join("\n"),
    tags: ["warmup", "deliverability", "inbox", "spam", "reputation"],
  },
  {
    id: "inbox-3",
    slug: "custom-smtp-setup",
    title: "Setting Up a Custom SMTP Inbox",
    category: "inbox-setup",
    content: [
      "# Setting Up a Custom SMTP Inbox",
      "",
      "If you're not using Gmail or Outlook, you can connect any email provider that supports SMTP.",
      "",
      "## What you'll need",
      "",
      "- SMTP server: e.g. smtp.yourprovider.com",
      "- SMTP port: usually 587 (STARTTLS) or 465 (SSL)",
      "- IMAP server: e.g. imap.yourprovider.com",
      "- IMAP port: usually 993",
      "- Email address and password (or app password if 2FA is enabled)",
      "",
      "## Steps",
      "",
      "1. Go to **Settings > Connected Inboxes > + Add Inbox > Other provider**.",
      "2. Enter your SMTP and IMAP details.",
      "3. Click **Connect** - ConvergeFlow sends a test email to verify the connection.",
      "",
      "## App passwords",
      "",
      "If your provider requires 2FA, generate an app password from your email provider's security settings.",
    ].join("\n"),
    tags: ["smtp", "imap", "custom", "inbox", "email", "provider"],
  },

  // ── Campaigns ────────────────────────────────────────────────────────────
  {
    id: "camp-1",
    slug: "creating-your-first-campaign",
    title: "Creating Your First Campaign",
    category: "campaigns",
    content: [
      "# Creating Your First Campaign",
      "",
      "A campaign is a sequence of emails sent to a list of leads over a set schedule.",
      "",
      "## Steps",
      "",
      "1. Go to **Emails** and click **New Campaign**.",
      "2. Give your campaign a name and select a **target audience**.",
      "3. Choose a **writing style** - Concise, Conversational, Executive, or Technical.",
      "4. Set a **goal**: book a meeting, generate interest, or drive traffic.",
      "5. AI will draft your first 3-step sequence. Edit any email before launching.",
      "6. Set your **send window** (e.g. Mon-Fri, 9am-5pm) and daily limit.",
      "7. Click **Launch**.",
      "",
      "## Email sequence structure",
      "",
      "- **Step 1** - Introduction, value prop",
      "- **Step 2** - Follow-up (sent 3 days after no reply)",
      "- **Step 3** - Breakup email (sent 5 days after step 2)",
      "",
      "## Stopping for replies",
      "",
      "When a lead replies, ConvergeFlow automatically removes them from the sequence.",
    ].join("\n"),
    tags: ["campaign", "email", "sequence", "outreach", "launch"],
  },
  {
    id: "camp-2",
    slug: "reading-campaign-analytics",
    title: "Reading Campaign Analytics",
    category: "campaigns",
    content: [
      "# Reading Campaign Analytics",
      "",
      "The Analytics page shows you how your campaigns are performing in real time.",
      "",
      "## Key metrics",
      "",
      "- **Open rate** - percentage of recipients who opened at least one email. Benchmark: 25-40%.",
      "- **Reply rate** - percentage who replied. Good cold email reply rates are 5-15%.",
      "- **Interested rate** - replies flagged as positive. Aim for 2-5%.",
      "- **Unsubscribes** - leads who opted out.",
      "- **Bounces** - invalid email addresses.",
      "",
      "## Reading the funnel",
      "",
      "Sent -> Opened -> Replied -> Interested -> Booked",
      "",
      "Each stage is a conversion. If open rate is high but reply rate is low, improve your email body.",
      "",
      "## Exporting data",
      "",
      "Click **Export CSV** on any chart to download the raw data.",
    ].join("\n"),
    tags: ["analytics", "open rate", "reply rate", "metrics", "reporting"],
  },

  // ── Troubleshooting ───────────────────────────────────────────────────────
  {
    id: "ts-1",
    slug: "emails-going-to-spam",
    title: "Emails Going to Spam",
    category: "troubleshooting",
    content: [
      "# Emails Going to Spam",
      "",
      "If your emails are landing in spam, here are the most common causes and fixes.",
      "",
      "## Check your DNS records",
      "",
      "Go to **Settings > Domains** and verify all three records (SPF, DKIM, DMARC) show a green checkmark.",
      "",
      "## Check your domain reputation",
      "",
      "Use MXToolbox to check if your domain or IP is on a blocklist.",
      "",
      "## Review your email content",
      "",
      "- Avoid spam trigger words: 'guaranteed', 'free money', 'act now'",
      "- Don't use too many links in a single email",
      "- Personalize with the recipient's first name and company",
      "",
      "## Warming up",
      "",
      "If your inbox is less than 14 days old, some deliverability issues are normal. Check **Deliverability** for your warmup score.",
    ].join("\n"),
    tags: ["spam", "deliverability", "DNS", "blocklist", "warmup", "troubleshooting"],
  },
  {
    id: "ts-2",
    slug: "campaign-not-sending",
    title: "Campaign Not Sending Emails",
    category: "troubleshooting",
    content: [
      "# Campaign Not Sending Emails",
      "",
      "If your campaign is active but emails aren't going out, here are the most likely reasons.",
      "",
      "## Your inbox is disconnected",
      "",
      "Go to **Settings > Connected Inboxes** and check the status. If it shows 'Error', reconnect your inbox.",
      "",
      "## Send window is outside current time",
      "",
      "Check your campaign's send window. Emails queue until the next window opens.",
      "",
      "## Daily sending limit reached",
      "",
      "ConvergeFlow enforces a daily sending cap per inbox. Sends resume the next day.",
      "",
      "## All leads have been processed",
      "",
      "If every lead has received all emails (or unsubscribed), there are no more sends. Check the campaign's Lead Status breakdown.",
    ].join("\n"),
    tags: ["campaign", "troubleshooting", "not sending", "inbox", "limit"],
  },
];

/**
 * Search articles by title, content, or tags.
 * Returns all articles when query is empty.
 */
export function searchArticles(query: string): Article[] {
  const q = query.trim().toLowerCase();
  if (!q) return articles;

  return articles.filter((a) => {
    return (
      a.title.toLowerCase().includes(q) ||
      a.content.toLowerCase().includes(q) ||
      a.tags.some((t) => t.toLowerCase().includes(q))
    );
  });
}

/** Returns a single article by slug, or undefined if not found. */
export function getArticleBySlug(slug: string): Article | undefined {
  return articles.find((a) => a.slug === slug);
}
